server:
  port: 8082

spring:
  application:
    name: mall-demo
  datasource:
    url: jdbc:mysql://localhost:3306/star_platform?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 111

logging:
  level:
    root: info
