server:
  port: 8080

logging:
  level:
    root: info
  file:
    path: ../log/
  application:
    name: skeleton
  datasource:
    url: jdbc:mysql://localhost:3306/skeleton?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印


# 自定义变量
file:
  path: E:/temp/files


spring:
  application:
    name: skeleton
  profiles:
    active: dev

elasticsearch:
  host: 8.131.66.135
  port: 9200
  user: elastic
  pwd: 123456

management: #开启监控管理，优雅停机
  server:
    ssl:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true #启用shutdown端点
