server:
  port: 8080

logging:
  level:
    root: info

#spring:
#  application:
#    name: skeleton
#  datasource:
#    url: jdbc:mysql://localhost:3306/skeleton?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印


# 自定义变量
file:
  path: E:/temp/files
